"""autogenerated by genpy from rlbot3/motorsPWM.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motorsPWM(genpy.Message):
  _md5sum = "7b3d28eca08e2b533d7dacc9d4ded039"
  _type = "rlbot3/motorsPWM"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool pwm_enable
uint16 pwm_l
uint16 pwm_r

"""
  __slots__ = ['pwm_enable','pwm_l','pwm_r']
  _slot_types = ['bool','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pwm_enable,pwm_l,pwm_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motorsPWM, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pwm_enable is None:
        self.pwm_enable = False
      if self.pwm_l is None:
        self.pwm_l = 0
      if self.pwm_r is None:
        self.pwm_r = 0
    else:
      self.pwm_enable = False
      self.pwm_l = 0
      self.pwm_r = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B2H.pack(_x.pwm_enable, _x.pwm_l, _x.pwm_r))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.pwm_enable, _x.pwm_l, _x.pwm_r,) = _struct_B2H.unpack(str[start:end])
      self.pwm_enable = bool(self.pwm_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B2H.pack(_x.pwm_enable, _x.pwm_l, _x.pwm_r))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.pwm_enable, _x.pwm_l, _x.pwm_r,) = _struct_B2H.unpack(str[start:end])
      self.pwm_enable = bool(self.pwm_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B2H = struct.Struct("<B2H")
